_welcome:
    path: /
    defaults: {_controller: AppBundle:Default:index}
news:
    path: /news/{page}
    defaults: {_controller: AppBundle:News:index, page: 1}
    requirements:
        page:  \d+
news_show:
    path: /news/show/{id}
    defaults: {_controller: AppBundle:News:show}
    requirements:
        id:  \d+
clanwar:
    path: /clanwar/{page}
    defaults: {_controller: AppBundle:Clanwar:index, page: 1}
    requirements:
        page:  \d+
clanwar_show:
    path: /clanwar/show/{id}
    defaults: {_controller: AppBundle:Clanwar:show}
    requirements:
        id:  \d+
forum:
    path: /forum
    defaults: { _controller: AppBundle:Forum:index}
forum_category_show:
    path: /forum/category/{id}
    defaults: {_controller: AppBundle:Forum:category}
    requirements:
        id:  \d+
forum_thread_show:
    path: /forum/thread/{id}/{page}
    defaults: {_controller: AppBundle:Forum:thread, page: 1}
    requirements:
        id: \d+
        page: \d+
user:
    path: /user
    defaults: {_controller:AppBundle:User:index}
user_login:
    path: /user/login
    defaults: { _controller: AppBundle:User\Login:login }
login_check:
    path: /login_check
user_registration:
    path: /user/register
    defaults: {_controller: AppBundle:User\Registration:register}
user_registration_checkmail:
    path: /user/checkmail
    defaults: {_controller: AppBundle:User\Registration:checkMail}
user_registration_confirm:
    path: /user/confirmregistration/{username}/{token}
    defaults: {_controller: AppBundle:User\Registration:checkToken}
