# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    pw_enc_cost: 15


services:
    security.password_encoder:
        class: AppBundle\Security\PasswordEncoder
        arguments: ['%pw_enc_cost%']
    login_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        arguments: ['@security.password_encoder']
    db_user_provider:
        class: AppBundle\Security\User\UserProvider
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AppBundle\Entity\Security\User ]
        calls:
            - [setPwEncoder, ["@security.password_encoder"]]
    userdata_provider:
        class: AppBundle\Provider\UserProvider
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AppBundle\Entity\UserData ]
    login_listener:
        class: 'AppBundle\Listener\LoginListener'
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

