AppBundle\Entity\ClanwarComments:
    type: entity
    table: clanwar_comments
    indexes:
        author:
            columns:
                - author
        cw_id:
            columns:
                - cw_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        author:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author:
                    referencedColumnName: id
            orphanRemoval: false
        cw:
            targetEntity: Clanwar
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cw_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
