AppBundle\Entity\Clanwar:
    type: entity
    table: clanwar
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        opponentName:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: opponent_name
        opponentTag:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: opponent_tag
        maps:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        pointsOwn:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: points_own
        pointsOpponents:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: points_opponents
        date:
            type: datetime
            nullable: false
        lineupOwn:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: lineup_own
        lineupOpponent:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: lineup_opponent
        report:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
