AppBundle\Entity\ForumPost:
    type: entity
    table: forum_post
    indexes:
        author:
            columns:
                - author
        thread_id:
            columns:
                - thread_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        author:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author:
                    referencedColumnName: id
            orphanRemoval: false
        thread:
            targetEntity: ForumThread
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                thread_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
