AppBundle\Entity\ForumThread:
    type: entity
    table: forum_thread
    indexes:
        category_id:
            columns:
                - category_id
        author:
            columns:
                - author
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        access:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        category:
            targetEntity: ForumCategory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        author:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
