AppBundle\Entity\Navigation\NavigationCategory:
    type: entity
    table: navigationcategory
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        transkey:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: transKey
        access:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
