AppBundle\Entity\Navigation\NavigationItem:
    type: entity
    table: navigationitem
    indexes:
        category:
            columns:
                - category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        transkey:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        route:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        category:
            targetEntity: Navigationcategory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
