AppBundle\Entity\NewsArticle:
    type: entity
    table: news_article
    indexes:
        author:
            columns:
                - author
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    manyToOne:
        author:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
