AppBundle\Entity\NewsComment:
    type: entity
    table: news_comment
    indexes:
        article_id:
            columns:
                - article_id
                - author
        author:
            columns:
                - author
        IDX_C3904E8A7294869C:
            columns:
                - article_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    manyToOne:
        article:
            targetEntity: NewsArticle
            cascade: []
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                article_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        author:
            targetEntity: User
            cascade: []
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author:
                    referencedColumnName: id
                    onDelete:
            orphanRemoval: false
    lifecycleCallbacks: {  }
