AppBundle\Entity\UserData:
    type: entity
    table: user_data
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: last_name
        birthDate:
            type: datetime
            nullable: true
            column: birth_date
        playerName:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: player_name
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
