AppBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: AUTO
    fields:
        regDate:
            type: datetime
            nullable: false
            column: registration_date
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
